### PR TITLE
Get child process PID from Highlander server

### PR DESCRIPTION
**Pull request by juulSme**
The global registered process is not the actual running server but the wrapping Highlander process. To interact with the actual server, its PID is required. Now it can only be found using something (as far as I know) like:

```elixir
Node.list() |> Enum.find_value(&:rpc.call(&1, Process, :whereis, [MyServer]))

# or

:global.whereis_name({Highlander, MyServer})
|> :sys.get_state()
|> Map.get(:pid)
|> Supervisor.which_children()
|> case do
  [{_, pid, _, _}] -> pid
end
```
...which is not very nice.

This PR adds a `handle_call(:get_pid, _, _)` to the Highlander server, enabling an easier flow.

Also, I've added Github Actions CI and updated the dependencies.

### CODE REVIEW

**Comment by juulSme** [comment]
@derekkraan?

**Comment by lud** [comment]
I think you can just give another `{:global, name}` to you actual child, just by providing the name in the `GenServer.start_link/3` options. If the name is taken for some reason, it will try to start again and again, that will make the hidden supervisor started from the highlander process to crash, which will make the highlander process itself crash (because it does not have a `handle_info` clause for that exit signal – that should be addressed).

But in case of net-split-then-rejoin the actual process will use the default termination method, which takes us back to the original problem, except this time the actual process of interest just has to exit (killed) or trap the exit and stop, it does not have to "think" about being restarted.

**Comment by lud** [comment]
@juulSme so I made a prototype, very very inspired from highlander but using a slightly different structure: https://github.com/lud/global_child


To add a global child this is the child spec to put under a supervisor:

```elixir
{GlobalChild, MyApp.MyGloblaSingleton}
```

In the meantime registering your process under Highlander with its own name works. I made this clone because I wanted to play with it and add tweaks, but highlander works well.

**Comment by juulSme** [comment]
@lud I missed your reply, thanks for thinking along! Too bad it seems this repo is dead :(

**Comment by lud** [comment]
Hi !

I made my clone of that library because I wanted some specific behaviour regarding supervision strategies (basically, I wanted the rest children to be restarted on all nodes when a global child died).

But Highlander still works well. You just need to use register your child process using global as you would do without highlander. You do not need to fetch the pid.

**Pull request closed without merging**
